// Grid Watch — browser client
const DONATE_URL = "#";
const TIP_URL = "";
const TIP_EMAIL = "tips@example.com";
const RADIUS_KM = 45;
let MAP=null, MARKERS=null, CURATED=[], LIVE=[], OSM=[];
const el=id=>document.getElementById(id);
const esc=s=>String(s??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function dist(a,b,c,d){const R=6371,r=x=>x*Math.PI/180,p=r(c-a),q=r(d-b),s=Math.sin(p/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(q/2)**2;return 2*R*Math.asin(Math.sqrt(s));}
function money(n){if(n==null)return null;if(n>=1e9)return `£${(n/1e9).toFixed(n%1e9?1:0)}bn`;if(n>=1e6)return `£${Math.round(n/1e6)}m`;return `£${Number(n).toLocaleString("en-GB")}`;}
async function loadData(){try{const[d,p,o]=await Promise.all([fetch("datacentres.json").then(r=>r.json()),fetch("planning.json").then(r=>r.json()).catch(()=>({items:[]})),fetch("datacentres-osm.json").then(r=>r.json()).catch(()=>({items:[]}))]);CURATED=(d.datacentres||[]).filter(x=>Number.isFinite(x.lat)&&Number.isFinite(x.lng));LIVE=(p.items||[]).filter(x=>Number.isFinite(x.lat)&&Number.isFinite(x.lng));OSM=(o.items||[]).filter(x=>Number.isFinite(x.lat)&&Number.isFinite(x.lng));}catch(e){CURATED=[];LIVE=[];OSM=[];}}
function showMsg(t){el("msg").textContent=t;el("msg").classList.remove("hidden");}function hideMsg(){el("msg").classList.add("hidden");}
async function run(raw){const pc=(raw||"").trim();if(!pc){showMsg("Pop a postcode in first.");return;}hideMsg();el("go").textContent="Looking…";let loc;try{const r=await fetch("https://api.postcodes.io/postcodes/"+encodeURIComponent(pc)),j=await r.json();if(j.status!==200||!j.result)throw 0;loc={lat:j.result.latitude,lng:j.result.longitude,place:j.result.admin_district||j.result.parish||"your area"};}catch(e){el("go").textContent="Explore my area";showMsg("That postcode didn't resolve. Check it and try again.");return;}el("go").textContent="Explore my area";const near=a=>a.map(x=>({...x,km:dist(loc.lat,loc.lng,x.lat,x.lng)})).filter(x=>x.km<=RADIUS_KM).sort((a,b)=>a.km-b.km);render(loc,near(CURATED),near(LIVE),near(OSM));}
function powerLabel(x){const mw=x.power_mw??x.est_mw;if(mw==null)return "";const st=(x.power_status|| (x.est_mw!=null?"Estimated":"Unknown"));const icon=/connected|operational/i.test(st)?"⚡":/contracted|accepted/i.test(st)?"🔌":/proposed|requested/i.test(st)?"🟡":"◌";return `<div class="meta"><b>${icon} Power:</b> ${esc(mw)} MW · ${esc(st)}${x.power_basis?` · ${esc(x.power_basis)}`:""}</div>`;}
function ownerLine(x){const chain=[x.operator,x.owner,x.ultimate_owner].filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i);const country=x.ownership_country||x.country;return chain.length?`<div class="op"><b>Operator / ownership:</b> ${chain.map(esc).join(" → ")}${country?` · ${esc(country)}`:""}</div>`:"";}
function curatedRow(x){const amt=money(x.investment_gbp);return `<div class="row"><div class="top"><div class="nm">${esc(x.name)}</div>${amt?`<div class="amt">${amt}</div>`:""}</div>${ownerLine(x)}<div class="meta">${esc(x.area||"")} · ${esc(x.status||"")} · <span class="dist">~${Math.round(x.km)}km away</span></div>${powerLabel(x)}${x.planning_ref?`<div class="meta"><b>Planning:</b> ${esc(x.planning_ref)}</div>`:""}${x.grid_operator?`<div class="meta"><b>Grid:</b> ${esc(x.grid_operator)}</div>`:""}${x.note?`<div class="note">${esc(x.note)}</div>`:""}${x.last_verified?`<div class="meta">Last verified: ${esc(x.last_verified)}</div>`:""}${x.source?`<a class="src" href="${esc(x.source)}" target="_blank" rel="noreferrer">Evidence ↗</a>`:""}</div>`;}
function liveRow(x){return `<div class="row"><div class="top"><div class="nm">${esc(x.authority||"Planning application")}</div><div class="dist">~${Math.round(x.km)}km</div></div><div class="note">${esc((x.description||"").slice(0,260))}${(x.description||"").length>260?"…":""}</div><div class="meta">${esc(x.address||x.postcode||"")}${x.date?" · "+esc(x.date):""}${x.status?" · "+esc(x.status):""}</div>${x.url?`<a class="src" href="${esc(x.url)}" target="_blank" rel="noreferrer">Planning record ↗</a>`:""}</div>`;}
function osmRow(x){return `<div class="row"><div class="top"><div class="nm">${esc(x.name||"Data centre")}</div><div class="dist">~${Math.round(x.km)}km</div></div><div class="op">${esc(x.operator||"Operator not mapped")} <span class="flag osm">OpenStreetMap</span></div>${x.status?`<div class="meta">${esc(x.status)}</div>`:""}${x.source?`<a class="src" href="${esc(x.source)}" target="_blank" rel="noreferrer">View OSM evidence ↗</a>`:""}</div>`;}
function render(loc,c,l,o){el("home").classList.add("hidden");el("results").classList.remove("hidden");window.scrollTo(0,0);const inv=c.reduce((s,x)=>s+(x.investment_gbp||0),0),total=c.length+o.length+l.length;el("r-lead").textContent=`Within ${RADIUS_KM}km of ${loc.place}:`;el("r-big").textContent=inv?money(inv):String(total);el("r-say").innerHTML=inv?`of announced investment appears in the <b>verified register</b> near you. Open-map and planning records are shown separately below.`:total?`${total===1?"mapped record sits":"mapped records sit"} near you across the verified, open-map and planning layers.`:`nothing is currently returned within ${RADIUS_KM}km. That does not prove no data centre exists or is planned.`;el("r-curated").innerHTML=c.length?c.map(curatedRow).join(""):`<div class="empty">No independently verified register entries within ${RADIUS_KM}km yet.</div>`;el("r-live").innerHTML=l.length?l.slice(0,50).map(liveRow).join(""):`<div class="empty">No planning records in the current open-data layer near you.</div>`;el("r-osm").innerHTML=o.length?o.slice(0,100).map(osmRow).join(""):`<div class="empty">No OpenStreetMap data-centre features returned near you.</div>`;drawMap(loc,c,l,o);el("donate").href=DONATE_URL;const share=`Grid Watch maps data-centre infrastructure, planning and grid demand around ${loc.place}, with the evidence behind the claims. #TheScouseOracle`;el("share").onclick=()=>navigator.share?navigator.share({text:share}).catch(()=>{}):navigator.clipboard?.writeText(share);}
function drawMap(loc,c,l,o){if(typeof L==="undefined")return;if(!MAP){MAP=L.map("map",{scrollWheelZoom:false}).setView([loc.lat,loc.lng],9);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"&copy; OpenStreetMap contributors",maxZoom:18}).addTo(MAP);MARKERS=L.layerGroup().addTo(MAP);}MARKERS.clearLayers();const b=[[loc.lat,loc.lng]];L.circleMarker([loc.lat,loc.lng],{radius:7}).bindPopup("You").addTo(MARKERS);c.forEach(x=>{L.circleMarker([x.lat,x.lng],{radius:9}).bindPopup(`<b>${esc(x.name)}</b><br>Verified register`).addTo(MARKERS);b.push([x.lat,x.lng]);});l.slice(0,80).forEach(x=>{L.circleMarker([x.lat,x.lng],{radius:5}).bindPopup("<b>Planning record</b>").addTo(MARKERS);b.push([x.lat,x.lng]);});o.slice(0,250).forEach(x=>{L.circleMarker([x.lat,x.lng],{radius:5}).bindPopup(`<b>${esc(x.name||"Data centre")}</b><br>OpenStreetMap`).addTo(MARKERS);b.push([x.lat,x.lng]);});if(b.length>1)MAP.fitBounds(b,{padding:[40,40],maxZoom:11});setTimeout(()=>MAP.invalidateSize(),60);}
function sendTip(){if(TIP_URL){window.open(TIP_URL,"_blank","noopener");return;}location.href=`mailto:${TIP_EMAIL}?subject=${encodeURIComponent("Grid Watch evidence tip")}&body=${encodeURIComponent("Location / postcode:\n\nPlanning reference:\n\nOperator / developer:\n\nPrimary source link:\n\nNotes:\n")}`;}
el("tip").addEventListener("click",sendTip);el("go").addEventListener("click",()=>run(el("pc").value));el("pc").addEventListener("keydown",e=>{if(e.key==="Enter")run(el("pc").value);});document.querySelectorAll(".examples button").forEach(b=>b.addEventListener("click",()=>{el("pc").value=b.dataset.pc;run(b.dataset.pc);}));el("again").addEventListener("click",()=>{el("results").classList.add("hidden");el("home").classList.remove("hidden");el("pc").value="";window.scrollTo(0,0);});loadData();