// Grid Watch — browser client
const DONATE_URL="#";
const TIP_URL="";
const TIP_EMAIL="tips@example.com";
const RADIUS_KM=45;
let MAP=null,MARKERS=null,CURATED=[],LIVE=[],OSM=[],GRID=[],OWNERSHIP=new Map(),GRID_CONTEXT=null;
const el=id=>document.getElementById(id);
const esc=s=>String(s??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function dist(a,b,c,d){const R=6371,r=x=>x*Math.PI/180,p=r(c-a),q=r(d-b),s=Math.sin(p/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(q/2)**2;return 2*R*Math.asin(Math.sqrt(s));}
function money(n){if(n==null)return null;if(n>=1e9)return `£${(n/1e9).toFixed(n%1e9?1:0)}bn`;if(n>=1e6)return `£${Math.round(n/1e6)}m`;return `£${Number(n).toLocaleString("en-GB")}`;}
async function loadData(){try{const[d,p,o,g,w]=await Promise.all([fetch("datacentres.json").then(r=>r.json()).catch(()=>({datacentres:[]})),fetch("planning.json").then(r=>r.json()).catch(()=>({items:[]})),fetch("datacentres-osm.json").then(r=>r.json()).catch(()=>({items:[]})),fetch("grid.json").then(r=>r.json()).catch(()=>({items:[],national_context:null})),fetch("ownership.json").then(r=>r.json()).catch(()=>({items:[]}))]);CURATED=(d.datacentres||[]).filter(x=>Number.isFinite(x.lat)&&Number.isFinite(x.lng));LIVE=(p.items||[]).filter(x=>Number.isFinite(x.lat)&&Number.isFinite(x.lng));OSM=(o.items||[]).filter(x=>Number.isFinite(x.lat)&&Number.isFinite(x.lng));GRID=(g.items||[]).filter(x=>Number.isFinite(x.lat)&&Number.isFinite(x.lng));GRID_CONTEXT=g.national_context||null;OWNERSHIP=new Map((w.items||[]).map(x=>[x.site_id,x]));}catch(e){CURATED=[];LIVE=[];OSM=[];GRID=[];OWNERSHIP=new Map();GRID_CONTEXT=null;}}
function showMsg(t){el("msg").textContent=t;el("msg").classList.remove("hidden");}function hideMsg(){el("msg").classList.add("hidden");}
async function run(raw){const pc=(raw||"").trim();if(!pc){showMsg("Pop a postcode in first.");return;}hideMsg();el("go").textContent="Looking…";let loc;try{const r=await fetch("https://api.postcodes.io/postcodes/"+encodeURIComponent(pc)),j=await r.json();if(j.status!==200||!j.result)throw 0;loc={lat:j.result.latitude,lng:j.result.longitude,place:j.result.admin_district||j.result.parish||"your area"};}catch(e){el("go").textContent="Explore my area";showMsg("That postcode didn't resolve. Check it and try again.");return;}el("go").textContent="Explore my area";const near=a=>a.map(x=>({...x,km:dist(loc.lat,loc.lng,x.lat,x.lng)})).filter(x=>x.km<=RADIUS_KM).sort((a,b)=>a.km-b.km);render(loc,near(CURATED),near(LIVE),near(OSM),near(GRID));}
function powerLabel(x){const mw=x.power_mw??x.est_mw;if(mw==null)return "";const st=(x.power_status||(x.est_mw!=null?"Estimated":"Unknown"));const icon=/connected|operational/i.test(st)?"⚡":/contracted|accepted/i.test(st)?"🔌":/proposed|requested/i.test(st)?"🟡":"◌";return `<div class="meta"><b>${icon} Power:</b> ${esc(mw)} MW · ${esc(st)}${x.power_basis?` · ${esc(x.power_basis)}`:""}</div>`;}
function ownerLine(x){const chain=[x.operator,x.owner,x.ultimate_owner].filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i);const country=x.ownership_country||x.country;return chain.length?`<div class="op"><b>Operator / ownership:</b> ${chain.map(esc).join(" → ")}${country?` · ${esc(country)}`:""}</div>`:"";}
function curatedRow(x){const amt=money(x.investment_gbp);return `<div class="row"><div class="top"><div class="nm">${esc(x.name)}</div>${amt?`<div class="amt">${amt}</div>`:""}</div>${ownerLine(x)}<div class="meta">${esc(x.area||"")} · ${esc(x.status||"")} · <span class="dist">~${Math.round(x.km)}km away</span></div>${powerLabel(x)}${x.planning_ref?`<div class="meta"><b>Planning:</b> ${esc(x.planning_ref)}</div>`:""}${x.grid_operator?`<div class="meta"><b>Grid:</b> ${esc(x.grid_operator)}</div>`:""}${x.note?`<div class="note">${esc(x.note)}</div>`:""}${x.last_verified?`<div class="meta">Last verified: ${esc(x.last_verified)}</div>`:""}${x.source?`<a class="src" href="${esc(x.source)}" target="_blank" rel="noreferrer">Evidence ↗</a>`:""}</div>`;}
function liveRow(x){const pm=(x.power_mentions||[]).map(p=>`${p.value} ${p.unit}`).join(", ");return `<div class="row"><div class="top"><div class="nm">${esc(x.authority||"Planning application")}</div><div class="dist">~${Math.round(x.km)}km</div></div><div class="note">${esc((x.description||"").slice(0,260))}${(x.description||"").length>260?"…":""}</div><div class="meta">${esc(x.nation||"")}${x.address?" · "+esc(x.address):""}${x.date?" · "+esc(x.date):""}${x.status?" · "+esc(x.status):""}</div>${pm?`<div class="meta"><b>Power mentioned in planning text:</b> ${esc(pm)} <span class="flag">unverified context</span></div>`:""}${x.url?`<a class="src" href="${esc(x.url)}" target="_blank" rel="noreferrer">Open planning source ↗</a>`:""}</div>`;}
function osmRow(x){const own=OWNERSHIP.get(x.id);let ownership="";if(own&&own.chain&&own.chain.length){const names=own.chain.map(c=>c.name).filter(Boolean);ownership=`<div class="meta"><b>Open ownership link:</b> ${names.map(esc).join(" → ")}${own.ultimate_parent_country?` · ${esc(own.ultimate_parent_country)}`:""} <span class="flag osm">Wikidata CC0</span></div>`;}return `<div class="row"><div class="top"><div class="nm">${esc(x.name||"Data centre")}</div><div class="dist">~${Math.round(x.km)}km</div></div><div class="op">${esc(x.operator||"Operator not mapped")} <span class="flag osm">OpenStreetMap</span></div>${x.status?`<div class="meta">${esc(x.status)}</div>`:""}${ownership}${x.source?`<a class="src" href="${esc(x.source)}" target="_blank" rel="noreferrer">View OSM evidence ↗</a>`:""}</div>`;}
function gridRow(x){return `<div class="row"><div class="top"><div class="nm">${esc(x.name||"High-voltage substation")}</div><div class="dist">~${Math.round(x.km)}km</div></div><div class="meta"><b>Mapped voltage:</b> ${esc(x.voltage_label||"")}${x.operator?` · ${esc(x.operator)}`:""}</div><div class="note">Geographic grid context only. Proximity does not prove a data centre connects to this substation.</div>${x.source?`<a class="src" href="${esc(x.source)}" target="_blank" rel="noreferrer">OpenStreetMap source ↗</a>`:""}</div>`;}
function gridContext(){if(!GRID_CONTEXT)return "";const c=GRID_CONTEXT;return `<div class="context"><b>Britain's demand-connection queue:</b> Ofgem reported ${esc(c.demand_connection_applications_gw)} GW of demand-connection applications on ${esc(c.as_of)}, up from ${esc(c.previous_demand_connection_applications_gw)} GW in under a year, with data-centre projects accounting for at least ${esc(c.data_centre_component_at_least_gw)} GW. <b>These are applications/queue figures, not current consumption.</b> <a href="${esc(c.source)}" target="_blank" rel="noreferrer">Ofgem source ↗</a></div>`;}
function render(loc,c,l,o,g){el("home").classList.add("hidden");el("results").classList.remove("hidden");window.scrollTo(0,0);const inv=c.reduce((s,x)=>s+(x.investment_gbp||0),0),total=c.length+o.length+l.length;el("r-lead").textContent=`Within ${RADIUS_KM}km of ${loc.place}:`;el("r-big").textContent=inv?money(inv):String(total);el("r-say").innerHTML=inv?`of announced investment appears in the <b>verified register</b> near you. Open-map, planning and electricity-infrastructure records are shown separately below.`:total?`${total===1?"mapped data-centre/planning record sits":"mapped data-centre/planning records sit"} near you. Grid infrastructure is shown separately and is not counted as a data centre.`:`no data-centre or planning record is currently returned within ${RADIUS_KM}km. That does not prove none exists or is planned.`;el("r-curated").innerHTML=c.length?c.map(curatedRow).join(""):`<div class="empty">No open-evidence verified register entries within ${RADIUS_KM}km yet.</div>`;el("r-grid-context").innerHTML=gridContext();el("r-grid").innerHTML=g.length?g.slice(0,75).map(gridRow).join(""):`<div class="empty">No 132 kV+ OpenStreetMap substations returned within ${RADIUS_KM}km.</div>`;el("r-live").innerHTML=l.length?l.slice(0,75).map(liveRow).join(""):`<div class="empty">No mappable open-licensed planning candidates near you in the current feeds.</div>`;el("r-osm").innerHTML=o.length?o.slice(0,125).map(osmRow).join(""):`<div class="empty">No OpenStreetMap data-centre features returned near you.</div>`;drawMap(loc,c,l,o,g);el("donate").href=DONATE_URL;const share=`Grid Watch maps open data on data-centre infrastructure, planning and high-voltage grid context around ${loc.place}. #TheScouseOracle`;el("share").onclick=()=>navigator.share?navigator.share({text:share}).catch(()=>{}):navigator.clipboard?.writeText(share);}
function drawMap(loc,c,l,o,g){if(typeof L==="undefined")return;if(!MAP){MAP=L.map("map",{scrollWheelZoom:false}).setView([loc.lat,loc.lng],9);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"&copy; OpenStreetMap contributors",maxZoom:18}).addTo(MAP);MARKERS=L.layerGroup().addTo(MAP);}MARKERS.clearLayers();const b=[[loc.lat,loc.lng]];L.circleMarker([loc.lat,loc.lng],{radius:7}).bindPopup("You").addTo(MARKERS);c.forEach(x=>{L.circleMarker([x.lat,x.lng],{radius:9}).bindPopup(`<b>${esc(x.name)}</b><br>Verified register`).addTo(MARKERS);b.push([x.lat,x.lng]);});l.slice(0,100).forEach(x=>{L.circleMarker([x.lat,x.lng],{radius:5}).bindPopup(`<b>Planning candidate</b><br>${esc(x.reference||"")}`).addTo(MARKERS);b.push([x.lat,x.lng]);});o.slice(0,300).forEach(x=>{L.circleMarker([x.lat,x.lng],{radius:5}).bindPopup(`<b>${esc(x.name||"Data centre")}</b><br>OpenStreetMap`).addTo(MARKERS);b.push([x.lat,x.lng]);});g.slice(0,100).forEach(x=>{L.circleMarker([x.lat,x.lng],{radius:4}).bindPopup(`<b>${esc(x.name||"Substation")}</b><br>${esc(x.voltage_label||"")}<br>Grid context only`).addTo(MARKERS);});if(b.length>1)MAP.fitBounds(b,{padding:[40,40],maxZoom:11});setTimeout(()=>MAP.invalidateSize(),60);}
function sendTip(){if(TIP_URL){window.open(TIP_URL,"_blank","noopener");return;}location.href=`mailto:${TIP_EMAIL}?subject=${encodeURIComponent("Grid Watch evidence tip")}&body=${encodeURIComponent("Location / postcode:\n\nPlanning reference:\n\nOperator / developer:\n\nOpen-data / primary source link:\n\nNotes:\n")}`;}
el("tip").addEventListener("click",sendTip);el("go").addEventListener("click",()=>run(el("pc").value));el("pc").addEventListener("keydown",e=>{if(e.key==="Enter")run(el("pc").value);});document.querySelectorAll(".examples button").forEach(b=>b.addEventListener("click",()=>{el("pc").value=b.dataset.pc;run(b.dataset.pc);}));el("again").addEventListener("click",()=>{el("results").classList.add("hidden");el("home").classList.remove("hidden");el("pc").value="";window.scrollTo(0,0);});loadData();